const hr = Array(40).fill("=").join("")

console.log(hr)
console.log("perf_storage")
console.log(hr)
require("./perf_storage").run()
console.log(hr)
console.log("perf_world")
console.log(hr)
require("./perf_world").run()
console.log(hr)
